Vagrant.configure(2) do |config|

    config.hostmanager.enabled = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true

    config.vm.define "puppet" do |puppet|
        # Puppetmaster on CentOS 7
        config.vm.provider "virtualbox" do |v|
            v.memory = 3072
        end
        puppet.vm.box = "centos/7"
        puppet.vm.hostname = "puppet.mylab.com"
        puppet.vm.network :private_network, ip: "10.0.20.10"
        puppet.hostmanager.aliases = %w(puppet)
        puppet.vm.provision "shell", inline: <<-SHELL
            # sudo yum update -y
            # sudo yum install ntp -y
            # sudo systemctl start ntpd
            # sudo systemctl enable ntpd
            # yum install wget -y
            # wget --content-disposition 'https://pm.puppet.com/cgi-bin/download.cgi?dist=el&rel=7&arch=x86_64&ver=latest'
            # tar -xzvf puppet-enterprise-2019.5.0-el-7-x86_64.tar.gz
            # cd puppet-enterprise-2019.5.0-el-7-x86_64/
            # (echo 1) | sudo ./puppet-enterprise-installer
        SHELL
    end

    config.vm.define "agentw" do |agentw|
        # Windows box slave
        agentw.vm.box = "devopsguys/Windows2012R2Eval"
        agentw.vm.hostname = "agentw.mylab.com"
        agentw.vm.network :private_network, ip: "10.0.20.11"
        agentw.hostmanager.aliases = %w(agentw)
    end
end